apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@mydomain.com
    privateKeySecretRef:
      name: http01-cluster-issuer-piv-key
    solvers:
    - http01:
        ingress:
          class: traefik
